### ISSUE TITLE
[backend / test] 테스트

### ISSUE THREAD

**Issue by savannah030** [Numble5/luvShort#22]

**Comment by urther** [comment]
@savannah030 
커밋 내용은 영어로 부탁드려용 ❤️ !!
완료된 이슈이신건가용? 그럼 닫아드리겠습니닷 멘션주세욥

**Comment by savannah030** [comment]
앞으로 테스트는 모두 #22에서 관리하려구요! 안 닫아주셔도 됩니다!!
커밋 영어로 작성하겠습니다 ✨

**Comment by urther** [comment]
@savannah030 넹넹 🕊
다른 close해야하는 이슈 있으면 말씀해주세용~~ 감사합니동

**Comment by savannah030** [comment]
@urther 넵!! 지금 당장 개발하지 않는 이슈는 다 닫아놨습니다 😄
