### ISSUE TITLE
[backend / feat] 엔티티 설계

### ISSUE THREAD

**Issue by savannah030** [Numble5/luvShort#9]

**Comment by savannah030** [comment]
![ERD ver1](https://user-images.githubusercontent.com/95270406/163763782-47478620-4971-44ec-bbc8-19d085075559.png)

**Comment by urther** [comment]
@savannah030 

1 . video에 hits 대신 좋아요를 누른 사용자의 닉네임? 이메일 (?) 이 있어야 나중에 매칭이 돼서 채팅이 가능하지 않을까.. (?) 라고 생각하는대..!
만약에 매칭이 되려면 어떻게 해야하나용..?
2. videoType : 유튜브 영상인지, 직접 올린 영상인지 저장할 필드(enum 타입) => 유투브 영상을 올리는거면 링크로 올리는건가요..?! 그러면 유투브 API도 끌어와야하는대 흑흑 🥲

**Comment by savannah030** [comment]
### 1-1 . video에 hits 대신 좋아요를 누른 사용자의 닉네임? 이메일 (?) 이 있어야 나중에 매칭이 돼서 채팅이 가능하지 않을까.. (?) 라고 생각하는대..! 

제가 중요한 부분을 언급을 안했네요 !! Video 엔티티에는 User 엔티티가 연관되어 있어서 User 객체 자체를 바로 갖고 올 수 있습니다 
[관련 코드](https://github.com/savannah030/luvShort/commit/e650a35b3e4e8c71ccb155ba73ae81e437d01fe2#r71547863) 

### 1-2. 만약에 매칭이 되려면 어떻게 해야하나용..?

매칭에 대하여 제가 구상한 방법은

사람1가 좋아요를 누르면 Likes 테이블에 likeUser(사람 1) 객체와 likeVideo(해당 영상) 객체를 저장
사람2가 좋아요를 누르면 Likes 테이블에 likeUser(사람 2) 객체와 likeVideo(해당 영상) 객체를 저장
...
이런 식으로 사람들이 누른 모든 좋아요 정보를 저장했다가

예를 들어 사람A가 사람B와 매칭을 원한다고 하면
> 1️⃣  User 엔티티의 `List<Video> myVideos` (사람A가 올린 영상들)을 for문으로 돌면서
2️⃣  Likes 테이블에서 likeVideo가 myVideo와 일치하는 경우를 찾는다.
3️⃣  그 중 사람B가 있으면 매칭한다.

이정도로 생각했습니다.

2️⃣ 에서 성능 문제를 좀 생각해봐야 할 것도 같은데.. 암튼 현재 생각은 그렇습니다 ㅎㅎ 구현하다 아니다 싶으면 다른 방법을 생각할수도 있을 것 같아요 
[관련 코드](https://github.com/savannah030/luvShort/commit/d750cb2564336d0452ad5293e5ba44e93752f96a#r71548801) 


### 2. videoType : 유튜브 영상인지, 직접 올린 영상인지 저장할 필드(enum 타입) => 유투브 영상을 올리는거면 링크로 올리는건가요..?! 그러면 유투브 API도 끌어와야하는대 흑흑 🥲

가이드라인에 '임베드 영상 업로드는 YOUTUBE에 올라와있는 영상을 그대로 가져오는 것이고' 라고 했으니 링크 갖고 와야 하지 않을까요?? 
전 그냥 유튜브 링크 입력받는 input 만들면 된다고 생각했는데.. 👉 👈 
영상 재생할 때는 유튜브 API 필요할 것 같기도 한데.. 이 부분도 좀 더 생각해봐야 할 것 같습니다 
제가 영상 업로드, 스트리밍 구현 방법을 잘 몰라서 열심히 찾아봐야 할 것 같아요 😭

**Comment by urther** [comment]
@savannah030 

추가적으로, **회원가입 날짜** 와 최근 **로그인 날짜**가 user 데이터에 있어야합니다.
그리고 회원 탈퇴 진행할 때, 바로 db에서 삭제를 안하는걸로 알고 있는데 그 부분도 어떻게 하실건지 알려주세요 '-'

**Comment by savannah030** [comment]
@urther
회원가입 날짜는 User의 createdDate이고 , 최근 로그인 날짜는 updateDate로 구현하면 될 것 같습니다
(모든 엔티티는 BaseEntity를 상속받아 생성날짜와 수정날짜 자동저장 가능합니다)
회원 탈퇴의 경우 User의 status 필드 추가하겠습니다!!

**Comment by urther** [comment]
@savannah030 하 진짜 죄송해요. 근데 저희 비디오 생성날짜는 어떻게 알 수 있나요 ?

**Comment by savannah030** [comment]
괜찮아용!! Video에도 createdDate 있으니까 Video 엔티티 생성할 때 날짜 자동저장할 수 있어요!
![erd ver1_baseentity까지](https://user-images.githubusercontent.com/95270406/163995630-4e9c341d-39f6-42fc-b851-d2b78c76d0f6.png)
복잡해서 ERD에서 뺐었는데 원래 ERD 이렇게 생겼어요 !! 모든 엔티티가 BaseEntity를 상속받아요

``` java
package com.example.backend.domain;

import lombok.Getter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import java.time.LocalDateTime;

@Getter
@MappedSuperclass // JPA Entity 클래스들이 BaseEntity를 상속할 경우 필드들(createdDate, updatedDate)도 칼럼으로 인식하도록 함
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @CreatedDate // Entity가 생성되어 저장될 때의 시간이 자동저장
    private LocalDateTime createdDate;

    @LastModifiedDate // 조회한 Entity의 값을 변경할 때의 시간이 자동 저장
    private LocalDateTime updatedDate;
}
```

**Comment by urther** [comment]
오 감사합니닷 🙏
